version: "3.8"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./tmp/db/var/lib/mysql
    container_name: rails_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: mysql_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_ja_0900_as_cs

  web:
    build: .
    command: "rails s -p 3000 -b '0.0.0.0'
    rm -f tmp/pids/server.pid"
    container_name: rails_web
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      BINDING: 0.0.0.0
    stdin_open: true
    tty: true
    links:
      - db
