version: "3.8"
services:
  server:
    build: ./server
    command: "bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./server:/myapp/server
    ports:
      - "${SERVER_PORT}:3000"
    # environment:
    # - DATABASE_URL=postgres://postgres:servers@db:5432/servers
    depends_on:
      - db
  db:
    image: "mysql:8.0.21"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - server_db:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  client:
    build: ./client
    command: "npm run start"
    volumes:
      - ./client:/myapp/client
    ports:
      - "${CLIENT_PORT}:3000"
volumes:
  server_db:
