source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.1' # 20/09/03 安定version

gem 'rails', '~> 6.0.3'

gem 'puma', '~> 5.0'
gem 'bootsnap', '~> 1.4', '>= 1.4.8', require: false
gem 'mysql2', '~> 0.5.2'
# gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '~> 3.2', '>= 3.2.1'
  gem 'spring', '~> 2.1', '>= 2.1.1'
  gem 'spring-watcher-listen', '~> 2.0', '>= 2.0.1'
  gem 'rubocop', require: false
end

gem 'tzinfo-data' #, platforms: [:mingw, :mswin, :x64_mingw, :jruby]
